### ISSUE TITLE
Review Ticket - James Lee

### ISSUE THREAD

**Issue by JL1080** [willcyber/tri3#12]
Individual GitHub pages (3 points)

- [ ] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime

- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by willcyber** [comment]
Individual GitHub pages (3 points)

- [ ] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

Comment: Very well organized. Everything is present. 1/1

- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime

Comment: -0.1 pt. Github is not linked. However, Replit is embedded and the code looks good. 0.9/1

- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

Comment: Everything looks good. Links to the code is present. Program runtime is also linked. The program works and meets the requirements. 1/1

Additional comments: There is a navbar that makes the github page more organized and easier to navigate,
Final score: 2.9/3
