### ISSUE TITLE
Review Ticket - Alex Do

### ISSUE THREAD

**Issue by AlexD017** [willcyber/tri3#4]
Scrum Team GitHub pages (2 points)

- [ ] Web Project: Project Description, Project Plans/Ideas/Wires, Time box

- [ ] Team Roles described, Project Owner or Sponsor described, Scrum Board started

Individual GitHub pages (3 points)

- [ ] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime

- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by Gabrielboudreau** [comment]
Scrum Team GitHub pages (2 points)

 1/1 Web Project: Project Description, Project Plans/Ideas/Wires, Time box

 1/1 Team Roles described, Project Owner or Sponsor described, Scrum Board started

Individual GitHub pages (3 points)

 1/1 GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

1/1 GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and Replit for runtime

1/1 GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime
