### ISSUE TITLE
Project Task - Alex Do

### ISSUE THREAD

**Issue by AlexD017** [willcyber/tri3#40]
# Score: 5/5 Graded by James Lee (Team Scrum Master)

Link to Individual Github Page: [here](https://alexd017.github.io/Tri3-IndivRepo/)

### GH Team Page and Individual Work
- [x] Project task on scrum board for week, due EOD Monday
- [x] Tangible coding artifacts for week
- [x] Comments, runtime, and drivers/testers for review
- [x] Project task used as review ticket, show sponsor objective completed, and coding reflection for week
- [x] Watch 2 of the 10 CB University Faculty Lectures to strengthen your foundation and make notes on your indi GH Pages

**Comment by JL1080** [comment]
# Score: 5/5 Graded by James Lee 

Link to Individual Github Page: [here](https://alexd017.github.io/Tri3-IndivRepo/)

### GH Team Page and Individual Work
- [x] Project task on scrum board for week, due EOD Monday
- [x] Tangible coding artifacts for week
- [x] Comments, runtime, and drivers/testers for review
- [x] Project task used as review ticket, show sponsor objective completed, and coding reflection for week
- [x] Watch 2 of the 10 CB University Faculty Lectures to strengthen your foundation and make notes on your indi GH Pages
