### ISSUE TITLE
Project Task - James Lee

### ISSUE THREAD

**Issue by JL1080** [willcyber/tri3#41]
# Score: 5/5 Graded by Alex Do (I am the Scrummaster so I had a teammember do it)

Link to Individual Github Page: [here](https://jl1080.github.io/tri3data1/)

### GH Team Page and Individual Work
- [x] Project task on scrum board for week, due EOD Monday
- [x] Tangible coding artifacts for week
- [x] Comments, runtime, and drivers/testers for review
- [x] Project task used as review ticket, show sponsor objective completed, and coding reflection for week
- [x] Watch 2 of the 10 CB University Faculty Lectures to strengthen your foundation and make notes on your indi GH Pages

**Comment by AlexD017** [comment]
# Score: 5/5 Graded by Alex Do
Comment: Had all requirements for the week project task coding + the CollegeBoard Notes. Also good comments for project task coding
### GH Team Page and Individual Work

- [x] Project task on scrum board for week, due EOD Monday
- [x] Tangible coding artifacts for week
- [x] Comments, runtime, and drivers/testers for review
- [x] Project task used as review ticket, show sponsor objective completed, and coding reflection for week
- [x] Watch 2 of the 10 CB University Faculty Lectures to strengthen your foundation and make notes on your indi GH Pages
