### ISSUE TITLE
Proctored MCQ Week1 - William Wu

### ISSUE THREAD

**Issue by willcyber** [willcyber/tri3#43]
### Grader: Katie Hickman Score: 5/5 (all requirements are fulfilled)

GH Indi Page and Review Ticket for following...
Start review ticket with study plan and study reflection for week, due EOD Monday 4/18
Finals-Quiz1 score/50 and corrections
Finals-Quiz2 score/50 and corrections
Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permits
Review ticket with Crossover Score on Monday 4/25 in class

**Comment by katiehickman** [comment]
**Grader: Katie Hickman Score: 5/5 (all requirements are fulfilled)**
Tangibles:
_Study Plan, Quiz Corrections, and Quiz Scores:_ https://github.com/willcyber/tri3/issues/39 
_Create Task:_ https://willcyber.github.io/createtask, https://github.com/willcyber/willcyber.github.io/wiki/Create-Task, and https://github.com/aidanywu/furious_five/blob/main/templates/minigames/rockpaperscissors.html
