### ISSUE TITLE
Proctored MCQ Week1 - Evan Sanchez

### ISSUE THREAD

**Issue by deimie** [willcyber/tri3#44]
Total Score: 4/5
Graded By: Bryon Lu

- [x] Start review ticket with study plan and study reflection for week, due EOD Monday 4/18
Monday: Working on create task
Tuesday: MCQ 1
Wednesday: Create Task Writeup
Thursday: MCQ 2
Friday: Create task revisions

- [x] Finals-Quiz1 score/50 and corrections
Score: 39/50

- [x] Finals-Quiz2 score/50 and corrections
Score 44/50

- [x] Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permits

- [x] Review ticket with Crossover Score on Monday 4/25 in class

**Comment by byronlu06** [comment]
Total Score: 3.5/5
Graded By: Byron Lu

- [x] Start review ticket with study plan and study reflection for week, due EOD Monday 4/18

Started review ticket with study plan

- [x] Finals-Quiz1 score/50 and corrections

Completed Finals-Quiz1 with score however no corrections -0.5

- [x] Finals-Quiz2 score/50 and corrections

Completed Finals-Quiz2 with score however no corrections -0.5

- [x] Create Task code/runtime and 1 min video are reviewed by another person, you may request Teacher review as time permits

Create Task has runtime and code, however video is missing -0.5

- [x] Review ticket with Crossover Score on Monday 4/25 in class
