### ISSUE TITLE
PBL Coder MCQ Week 2: Quiz 3 - Alex Do

### ISSUE THREAD

**Issue by AlexD017** [willcyber/tri3#45]
# Score: 3.5/4.5 Graded by James Lee (Crossover)

- [x] GH Team/Indi Page as applicable, Review Ticket, SCRUM Team graded
- [x] PBL project "tangibles" for two weeks.
- [ ] Quiz3 MCQ results
- [x] Quality of Work  /.5
- [x] Participation in Class 

Link to Individual Github Page: [here](https://alexd017.github.io/Tri3-IndivRepo/)

Link to Individual Repository: [here](https://github.com/AlexD017/Tri3-IndivRepo#readme)

Link to tangibles: [here](https://alexd017.github.io/Tri3-IndivRepo/week6/tangible)

Link to MCQ score: [here](https://alexd017.github.io/Tri3-IndivRepo/week6/mcq3score)

**Comment by JL1080** [comment]
## Grade 3.5/4.5  Graded by James Lee 
- [x] GH Team/Indi Page as applicable, Review Ticket, SCRUM Team graded
- SCRUM team graded and they looked over the tangibles work. Said it was good and contributed to the project and was one of the tasks the sponsors wanted.
- [x] PBL project "tangibles" for two weeks.
- Good tangibles especially for the scientific calculator and fixing the navbar as it was a big issue for us 
- [ ] Quiz3 MCQ results
- Got lower than 50% so can't give the point 
- [x] Quality of Work +.5 
- Very good quality of work and the calculator is very useful. Also many functions on it which is useful for college students
- [x] Participation in Class 
- Participates in class and gets his work done. Especially for the skit and other code related activities

Link to Individual Github Page: [here](https://alexd017.github.io/Tri3-IndivRepo/)

Link to Individual Repository: [here](https://github.com/AlexD017/Tri3-IndivRepo#readme)

Link to tangibles: [here](https://alexd017.github.io/Tri3-IndivRepo/week6/tangible)
