### ISSUE TITLE
Proctored MCQ Week2 : Quiz3 and Create Task review - William Wu

### ISSUE THREAD

**Issue by willcyber** [willcyber/tri3#46]
### Peer Reviewer: Evan Sanchez

**Comment by willcyber** [comment]
GH Indi Page, Review Ticket, Crossover graded, Study Plan
Create Task and Create Task Crossover Review comments (completed by Thu)
Quiz3 MCQ results and test corrections
Participation
Quality of Work

**Comment by deimie** [comment]
Score: 4.25/4.5

- GH Indi Page, Review Ticket, Crossover graded, Study Plan - 1/1
[Link](https://github.com/willcyber/tri3/issues/39)

- Create Task and Create Task Crossover Review comments (completed by Thu) - .75/1
[Link](https://willcyber.github.io/createtask)  
_-.25, no written review comments. Only verbally discussed_

- Quiz3 MCQ results and test corrections - 1/1
[Link](https://github.com/willcyber/tri3/issues/39)

- Participation - 1/1
_Always seems to be on task_

- Quality of Work - .5/.5
_Quality of work meets CSP standards._
