### ISSUE TITLE
Proctored MCQ Week2 : Quiz3 and Create Task review - Evan Sanchez

### ISSUE THREAD

**Issue by deimie** [willcyber/tri3#47]
Score: 4.25/4.5
Graded by: William Wu

GH Indi Page, Review Ticket, Crossover graded, Study Plan
Create Task and Create Task Crossover Review comments (completed by Thu)
Quiz3 MCQ results and test corrections
Participation
Quality of Work

Study Plan:
Monday: MCQ 3
Tuesday: Corrections for MCQ
Wednesday: Comment all JS fully
Thursday: Working on write up for create
Friday: Submit create task

**Comment by willcyber** [comment]
Score: 4.25/4.5
Graded By: William Wu
GH Indi Page, Review Ticket, Crossover graded, Study Plan (displayed above)
Comments; Review ticket and study plan present. 1/1
[Create Task and Create Task Crossover Review comments (completed by Thu)](https://deimie.github.io/individual/gh-pages/createTask)
Comments: Evan and I had talked about our create tasks and how they satisfied the requirements. However, we did not document any of the comments 0.75/1
[Quiz3 MCQ results and test corrections](https://deimie.github.io/individual/gh-pages/apTestCorrections)
Comments: All the corrections are present and displayed on the github page 1/1
Participation
Comments: In class every day and doing relevant work. 1/1
Quality of Work
Comments: The quality of work is meets the requirements. 0.5/0.5
