### ISSUE TITLE
PBL Coder AP Exams Week 1 - Alex Do

### ISSUE THREAD

**Issue by AlexD017** [willcyber/tri3#49]
# Score: 2/2 Graded by James Lee (Crossover)

- [x] GH Team/Indi Page as applicable, Review Ticket with links to issues, SCRUM Team graded
- [x] PBL project "tangibles".

Link to Individual Github Page: [here](https://alexd017.github.io/Tri3-IndivRepo/)

Link to Individual Repository: [here](https://github.com/AlexD017/Tri3-IndivRepo#readme)

Link to tangible: [here](https://alexd017.github.io/Tri3-IndivRepo/week7/tangible)

**Comment by JL1080** [comment]
# Score: 2/2 Graded by James Lee (Crossover)

- [x] GH Team/Indi Page as applicable, Review Ticket with links to issues, SCRUM Team graded
- The Github page and the page looks good. Team graded it and thought it was good and new feature.
- [x] PBL project "tangibles".
- Good tangibles with simple conversion feature

Link to Individual Github Page: [here](https://alexd017.github.io/Tri3-IndivRepo/)

Link to Individual Repository: [here](https://github.com/AlexD017/Tri3-IndivRepo#readme)

Link to tangible: [here](https://alexd017.github.io/Tri3-IndivRepo/week7/tangible)
