### ISSUE TITLE
Review Ticket - Evan Sanchez

### ISSUE THREAD

**Issue by deimie** [willcyber/tri3#5]
Individual GitHub pages (3 points)

- [x] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders (Links to an external site.)](https://cspcoders.nighthawkcodingsociety.com/))

- [x] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime

- [x] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

**Comment by Pitsco** [comment]
4.5/5

1.  Web Project: Project Description, Project Plans/Ideas/Wires, Timebox
Project Description:
Project description is given with what the general idea of the website potentially will be about. The time box is given too. 
[tangible](https://github.com/willcyber/tri3)
