### ISSUE TITLE
Proctored MCQ Quiz 5 - Evan Sanchez

### ISSUE THREAD

**Issue by deimie** [willcyber/tri3#50]
Score: 2/2
Graded by: Brian Zhang

- GH Indi Page, Review Ticket, Crossover graded, Study Plan

- Quiz5 MCQ results >50%, (1 or 0) and test corrections

**Study Plan -**
Monday: Study hall
Tuesday: Watch collegeboard videos to prep for test
Wednesday: Quiz 4
Thursday: Quiz 4 corrections
Friday: Prepare for AP exam & crossover grading

**Comment by BrianZhang2016** [comment]
# Score 2/2 Grader: Brian Zhang

## AP Test 4 (20/25) - [Corrections](https://deimie.github.io/individual/gh-pages/apTestCorrections)
<img width="864" alt="Screen Shot 2022-05-06 at 13 24 18" src="https://user-images.githubusercontent.com/89234480/167211650-f9d19175-0d72-4a9f-bcb1-b334e3bc8a3b.png">
