### ISSUE TITLE
AP Exam Week 1 MCQ - Quiz 5   James Lee

### ISSUE THREAD

**Issue by JL1080** [willcyber/tri3#51]
## Grade 2/2    Graded by Alex Do
- [ ] GH Team/Indi Page as applicable, Review Ticket with links to issues, SCRUM Team graded
- [ ] PBL project "tangibles".

Link to Tangibles  https://github.com/JL1080/tri3data1/blob/main/notes/week7tangibles.md
Github Page Link Github Page Link: https://jl1080.github.io/tri3data1/

**Comment by AlexD017** [comment]
## Grade 2/2    Graded by Alex Do
- [x] GH Team/Indi Page as applicable, Review Ticket with links to issues, SCRUM Team graded
Graded with scrum team, everything looks good on individual github page
- [x] PBL project "tangibles".
Nicely formatted weekly planner for PBL. Purpose of this matches with our project.

Link to Tangibles  https://github.com/JL1080/tri3data1/blob/main/notes/week7tangibles.md
Github Page Link Github Page Link: https://jl1080.github.io/tri3data1/
